### ISSUE TITLE
Can you give me your happly.h header 

### ISSUE THREAD

**Issue by ZMIOT** [BMark96/3DSSF_TrimmedIterativeClosestPoint#1]
when i run your code,i frist install the nanoflann lib 
can you give me you happyly.h
email:mr_zhoum@163.com

**Comment by 1099255210** [comment]
https://github.com/nmwsharp/happly/blob/master/happly.h
don't thank thank me

**Comment by BMark96** [comment]
Sorry @ZMIOT, I forgot to answer your question. As @1099255210 wrote, you can find the header in this repo: https://github.com/nmwsharp/happly
